id: I42FC2497
legacy_id: P007908
ocr_import_info:
  bdrc_scan_id: W23898
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T13:23:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:01:25.630395+00:00'
last_modified: 2022-09-02 13:01:35.523918
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23898
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23898
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་དབང་བསྟན་འཛིན་དར་རྒྱས་ཀྱི་གསུང་མགུར།
  author: གྲུབ་དབང་བསྟན་འཛིན་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.6332380767263651
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I3673:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3673
      total_pages: 250
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3673.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6332380767263651
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
