id: P007908
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23898
  title: གྲུབ་དབང་བསྟན་འཛིན་དར་རྒྱས་ཀྱི་གསུང་མགུར
  author: ''
  volumes:
    4f17db1f9f9342e980c03bfaa65a5b2b:
      image_group_id: I3673
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
